USE CinemaManagement;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Tickets;
TRUNCATE TABLE Screenings;
TRUNCATE TABLE Customers;
TRUNCATE TABLE CinemaRooms;
TRUNCATE TABLE Movies;
TRUNCATE TABLE staff;
TRUNCATE TABLE seats;
TRUNCATE TABLE genres;
TRUNCATE TABLE moviegenres;
TRUNCATE TABLE seattypes;

SET FOREIGN_KEY_CHECKS = 1;


